title: Ömer Eryılmaz -  Hayat kısa, kodlar uçuyor..
description: Teknolojik bilgiler içeren kişisel web sayfası. 
baseurl: "" # the subpath of your site, e.g. /blog deneme2
url: "http://omereryilmaz.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Ömer Eryılmaz
author-image:   omer-eryilmaz.jpg
author-job:     MSc Computer Engineer & Software Development Engineer
author-email:   omer-eryilmaz@hotmail.com # Add your email for contant form.
author-twitter: omreryilmaz # Add your twitter account
about-author:   I am a Computer Engineer focusing on Software Development. Always hungry to keep learning new technologies.

# Social settings
social-twitter:   omreryilmaz
social-facebook:
social-github:    omereryilmaz
social-pinterest: 
social-instagram: omereryilmaz_
social-youtube: 
social-vk:   
social-linkedin: omereryilmaz

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-51356316-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: omereryilmaz # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/page/:num/"


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
